# generte postionnal encoding matrix PE 

In [1]:
from positional_enoding import generate_postionnal_encoding_matrix
import numpy as np
from torch.nn import Softmax
tokenised_texte = ["the" , "cat" , "is" , "so" ]

PE_matrix = generate_postionnal_encoding_matrix(tokenised_texte=tokenised_texte)
print(PE_matrix)
print(np.shape(PE_matrix))


[[0.0, 1.0, 0.0, 0.03162277660168379], [0.8414709848078965, 0.5403023058681398, 0.02660964896937897, 0.01708585911584281], [0.9092974268256817, -0.4161468365471424, 0.02875450939299445, -0.013159718445627706], [0.1411200080598672, -0.9899924966004454, 0.004462606488904997, -0.03130631155733909]]
(4, 4)


# Create the embeding Matrix Xe

In [2]:


np.random.default_rng(42)
d_model = 4
Xe = np.random.rand(d_model,d_model)
Wq = np.random.rand(d_model,d_model)
Wk = np.random.rand(d_model,d_model)
Wv = np.random.rand(d_model,d_model)
X_embeding = Xe + PE_matrix
print(X_embeding)


[[ 0.70596524  1.40241028  0.31046752  0.39539553]
 [ 1.1231253   1.40051862  0.48159499  0.77966783]
 [ 1.87342603 -0.03615655  0.83847195  0.0985632 ]
 [ 0.14693267 -0.86099198  0.83911782  0.84906907]]


In [12]:
import torch
from torch import tensor

def attention(Xe,Wq,Wk,Wv,d_model):
    
    if Xe.shape[0] != Wq.shape[1] :
        raise Exception('dimension not correct')

    Q = np.matmul(Xe,Wq)

    if Xe.shape[0] != Wk.shape[1] :
            raise Exception('dimension not correct')

    K = np.matmul(Xe,Wk)

    if Xe.shape[0] != Wv.shape[1] :
            raise Exception('dimension not correct')

    V = np.matmul(Xe,Wv)

    Attention = np.matmul(Q,K.T)
    Attention = Attention / np.sqrt(d_model)
    Attention = tensor(Attention)
    softmax = Softmax(dim=-1)
    Attention = softmax(Attention)
    Attention = Attention.numpy()

    return Attention

In [13]:
A = attention(Xe,Wq,Wk,Wv,d_model)
print(A)

[[0.18104513 0.37478193 0.22787669 0.21629625]
 [0.15443477 0.42961636 0.20360129 0.21234758]
 [0.17318157 0.39360696 0.23159206 0.20161941]
 [0.17555126 0.39002995 0.21749532 0.21692347]]
