# generte postionnal encoding matrix PE 

In [2]:
from positional_enoding import generate_postionnal_encoding_matrix
import numpy as np
from torch.nn import Softmax
tokenised_texte = ["the" , "cat" , "is" , "so" ]

PE_matrix = generate_postionnal_encoding_matrix(tokenised_texte=tokenised_texte)
print(PE_matrix)
print(np.shape(PE_matrix))


[[0.0, 1.0, 0.0, 0.03162277660168379], [0.8414709848078965, 0.5403023058681398, 0.02660964896937897, 0.01708585911584281], [0.9092974268256817, -0.4161468365471424, 0.02875450939299445, -0.013159718445627706], [0.1411200080598672, -0.9899924966004454, 0.004462606488904997, -0.03130631155733909]]
(4, 4)


# Create the embeding Matrix Xe

In [3]:

np.random.default_rng(42)
d_model = 4
Xe = np.random.rand(d_model,d_model)
Wq = np.random.rand(d_model,d_model)
Wk = np.random.rand(d_model,d_model)
Wv = np.random.rand(d_model,d_model)
X_embeding = Xe + PE_matrix
print(X_embeding)


[[ 0.42698308  1.84098163  0.26304335  0.06269716]
 [ 1.14641904  0.61518285  0.72282153  0.21182116]
 [ 1.63727576  0.2386468   0.49498551  0.13624499]
 [ 0.16674481 -0.48564652  0.34653551  0.78123439]]


In [6]:
import torch
from torch import tensor

def attention(Xe,Wq,Wk,Wv,d_model):
    
    if Xe.shape[0] != Wq.shape[1] :
        raise Exception('dimension not correct')

    Q = np.matmul(Xe,Wq)

    if Xe.shape[0] != Wk.shape[1] :
            raise Exception('dimension not correct')

    K = np.matmul(Xe,Wk)

    if Xe.shape[0] != Wv.shape[1] :
            raise Exception('dimension not correct')

    V = np.matmul(Xe,Wv)

    Attention = np.matmul(Q,K.T)
    Attention = Attention / np.sqrt(d_model)
    Attention = tensor(Attention)
    softmax = Softmax(dim=-1)
    Attention = softmax(Attention)
    Attention = Attention.numpy()
    #Attention = np.matmul(Attention , V)

    return Attention

In [ ]:
A = attention(Xe,Wq,Wk,Wv,d_model)
print(A)


[[0.20954318 0.20987619 0.33130634 0.24927428]
 [0.21596253 0.21979329 0.2999103  0.26433387]
 [0.19860353 0.19916923 0.35037609 0.25185115]
 [0.20624184 0.20629678 0.32650924 0.26095214]]


In [ ]:
WO = np.random.rand(d_model , d_model)
def layer_normalisation(X):
    mean = np.mean(X)
    std = np.std(X)
def layer_normalisation():
    Z = np.matmul(A,V)
    Y_attn = np.matmul(Z,WO)
