# generte postionnal encoding matrix PE 

In [1]:
from positional_enoding import generate_postionnal_encoding_matrix
import numpy as np
from torch.nn import Softmax
tokenised_texte = ["the" , "cat" , "is" , "so" ]

PE_matrix = generate_postionnal_encoding_matrix(tokenised_texte=tokenised_texte)
print(PE_matrix)
print(np.shape(PE_matrix))


[[0.0, 1.0, 0.0, 0.03162277660168379], [0.8414709848078965, 0.5403023058681398, 0.02660964896937897, 0.01708585911584281], [0.9092974268256817, -0.4161468365471424, 0.02875450939299445, -0.013159718445627706], [0.1411200080598672, -0.9899924966004454, 0.004462606488904997, -0.03130631155733909]]
(4, 4)


# Create the embeding Matrix Xe

In [3]:


np.random.default_rng(42)
d_model = 4
Xe = np.random.rand(d_model,d_model)
Wq = np.random.rand(d_model,d_model)
Wk = np.random.rand(d_model,d_model)
Wv = np.random.rand(d_model,d_model)
X_embeding = Xe + PE_matrix
print(X_embeding)


[[ 0.51870026  1.57041803  0.74070937  0.62290836]
 [ 1.25332327  0.73526514  0.53967793  0.60165304]
 [ 1.24261079  0.31753576  0.21370032  0.92710274]
 [ 0.65066128 -0.5503478   0.13645029  0.52899608]]


In [ ]:
def attention(Xe,Wq,Wk,Wv,d_model):
    
    if Xe.shape[0] != Wq.shape[1] :
        raise Exception('dimension not correct')

    Q = np.matmul(Xe,Wq)

    if Xe.shape[0] != Wk.shape[1] :
            raise Exception('dimension not correct')

    K = np.matmul(Xe,Wk)

    if Xe.shape[0] != Wv.shape[1] :
            raise Exception('dimension not correct')

    V = np.matmul(Xe,Wv)

    Attention = np.matmul(Q,K.T)
    Attention = Attention / np.sqrt(d_model)
    Attention = Softmax(Attention)
    Attention = np.matmul(Attention,V)

    return Attention