# Mapping the inputs with the ids

In [43]:
# necsaire imports
from positional_enoding import generate_postionnal_encoding_matrix
tokenised_texte = ["the" , "cat" , "is" , "so" ]
d_model = 4
np.random.default_rng(42)
import numpy as np
def Mapping_inputs_tokens_with_ids(input):
    toknised_id_text = np.zeros(len(tokenised_texte))
    for i in range(0,len(tokenised_texte)):
        id = np.random.randint(low=1,high=100)
        toknised_id_text[i] = id
    return toknised_id_text

id_table = Mapping_inputs_tokens_with_ids(tokenised_texte)
print(id_table)


[83. 23. 80.  5.]


# Defining the Masked Rule

In [44]:


def create_masked_matrix():
    M = np.zeros((d_model,d_model))
    for i in range(0,d_model):
        for j in range(0,d_model):
            if i >= j:
                M[i,j] = 0

            elif j > i:
                M[i,j] = float('-inf')

            return M
M = create_masked_matrix()
print(M)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# implementing the shfiting operation

In [45]:
def shifting_output(tokenised_texte ):
   return ["SOS"] + tokenised_texte

shifted_pos_text = shifting_output(tokenised_texte)


# calculation of Xdec

In [47]:
# frist calculate Postionnal encoding of the shifting input 
PE_matrix = generate_postionnal_encoding_matrix(tokenised_texte=shifted_pos_text)


TypeError: Postionnal_encoding_word() got multiple values for argument 'word_postion'