# Mapping the inputs with the ids

In [3]:
# necsaire imports
import numpy as np
#from positional_enoding import generate_postionnal_encoding_matrix
tokenised_texte = ["the" , "cat" , "is" , "so" ]
d_model = 4
np.random.default_rng(42)
import numpy as np
def Mapping_inputs_tokens_with_ids(input):
    toknised_id_text = np.zeros(len(tokenised_texte))
    for i in range(0,len(tokenised_texte)):
        id = np.random.randint(low=1,high=100)
        toknised_id_text[i] = id
    return toknised_id_text

id_table = Mapping_inputs_tokens_with_ids(tokenised_texte)
print(id_table)


[27. 93. 67. 40.]


# Defining the Masked Rule

In [4]:


def create_masked_matrix():
    M = np.zeros((d_model,d_model))
    for i in range(0,d_model):
        for j in range(0,d_model):
            if i >= j:
                M[i,j] = 0

            elif j > i:
                M[i,j] = float('-inf')

            return M
M = create_masked_matrix()
print(M)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# implementing the shfiting operation

In [5]:
def shifting_output(tokenised_texte ):
   return ["SOS"] + tokenised_texte

shifted_pos_text = shifting_output(tokenised_texte)


# calculation of Xdec

In [7]:

from positional_enoding import generate_postionnal_encoding_matrix
PE_matrix = generate_postionnal_encoding_matrix(tokenised_texte=shifted_pos_text , d_model=4)
print(PE_matrix)


[[0.0, 1.0, 0.0, 1.0], [0.8414709848078965, 0.5403023058681398, 0.009999833334166664, 0.9999500004166653], [0.9092974268256817, -0.4161468365471424, 0.01999866669333308, 0.9998000066665778], [0.1411200080598672, -0.9899924966004454, 0.02999550020249566, 0.9995500337489875], [-0.7568024953079282, -0.6536436208636119, 0.03998933418663416, 0.9992001066609779]]
