# Mapping the inputs with the ids

In [12]:

tokenised_texte = ["the" , "cat" , "is" , "so" ]
d_model = 4
np.random.default_rng(42)
import numpy as np
def Mapping_inputs_tokens_with_ids(input):
    toknised_id_text = np.zeros(len(tokenised_texte))
    for i in range(0,len(tokenised_texte)):
        id = np.random.randint(low=1,high=100)
        toknised_id_text[i] = id
    return toknised_id_text

id_table = Mapping_inputs_tokens_with_ids(tokenised_texte)
print(id_table)


[66. 45. 35. 44.]


# Defining the Masked Rule

In [ ]:


def create_masked_matrix():
    M = np.zeros((d_model,d_model))
    for i in range(0,d_model):
        for j in range(0,d_model):
            if i >= j:
                M[i,j] = 0

            elif j > i:
                M[i,j] = float('-inf')

            return M
M = create_masked_matrix()
print(M)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# implementing the shfiting operations

In [ ]:
def shifting_output(tokenised_texte ):
    
