# generte postionnal encoding matrix PE 

In [2]:
from positional_enoding import generate_postionnal_encoding_matrix
import numpy as np
from torch.nn import Softmax
tokenised_texte = ["the" , "cat" , "is" , "so" ]
PE_matrix = generate_postionnal_encoding_matrix(tokenised_texte=tokenised_texte , d_model= 4)
print(PE_matrix)
print(np.shape(PE_matrix))


[0.0, 1.0, 0.0, 1.0, 0.0]
[0.8415, 0.5403, 0.0251, 0.9997, 0.0006]
[0.9093, -0.4161, 0.0502, 0.9987, 0.0013]
[0.1411, -0.99, 0.0753, 0.9972, 0.0019]
[[0.0, 1.0, 0.0, 1.0], [0.8414709848078965, 0.5403023058681398, 0.009999833334166664, 0.9999500004166653], [0.9092974268256817, -0.4161468365471424, 0.01999866669333308, 0.9998000066665778], [0.1411200080598672, -0.9899924966004454, 0.02999550020249566, 0.9995500337489875]]
(4, 4)


# Create the embeding Matrix Xe

In [3]:

np.random.default_rng(42)
d_model = 4
Xe = np.random.rand(d_model,d_model)
Wq = np.random.rand(d_model,d_model)
Wk = np.random.rand(d_model,d_model)
Wv = np.random.rand(d_model,d_model)
X_embeding = Xe + PE_matrix
print(X_embeding)


[[ 0.58551147  1.12491271  0.46706113  1.68840043]
 [ 1.38222282  0.81390202  0.7716833   1.66855628]
 [ 1.05107434 -0.31850187  0.18276259  1.6606664 ]
 [ 0.82652372 -0.63942783  0.28518775  1.35759002]]


In [5]:
import torch
from torch import tensor

def attention(Xe,Wq,Wk,Wv,d_model):
    
    if Xe.shape[0] != Wq.shape[1] :
        raise Exception('dimension not correct')

    Q = np.matmul(Xe,Wq)

    if Xe.shape[0] != Wk.shape[1] :
            raise Exception('dimension not correct')

    K = np.matmul(Xe,Wk)

    if Xe.shape[0] != Wv.shape[1] :
            raise Exception('dimension not correct')

    V = np.matmul(Xe,Wv)

    Attention = np.matmul(Q,K.T)
    Attention = Attention / np.sqrt(d_model)
    Attention = tensor(Attention)
    softmax = Softmax(dim=-1)
    Attention = softmax(Attention)
    Attention = Attention.numpy()
    Attention = np.matmul(Attention , V)

    return Attention

In [6]:
A = attention(Xe,Wq,Wk,Wv,d_model)
print(A)


[[1.2598552  0.42527066 0.95982567 0.36945907]
 [1.28152286 0.43018337 0.97095199 0.37391763]
 [1.20570601 0.41009518 0.93158114 0.35881869]
 [1.2489259  0.42274621 0.95418066 0.3672189 ]]


In [8]:
WO = np.random.rand(d_model , d_model)
def layer_normalisation(X):
    epsilon = 10**-4
    mean = np.mean(X)
    std = np.std(X)
    return (X - mean) / (np.sqrt((std**2 + epsilon) ) )

def multi_head_projection(V , WO):
    Z = np.matmul(A,V)
    Y_att = np.matmul(Z,WO)
    return  Y_att

def first_risdual_addition(X_in,V,WO):
      Y_attn = multi_head_projection(V,WO)
      X_1 = X_in + Y_attn
      X_1 = layer_normalisation(d_model,d_model)
      return X_1

def postion_wise_feed_forward(X,W1,W2,bias1,bias2):
     X = np.matmul(X,W1) + bias1
     tensor_X = torch.tensor(X)
     tensor_X = torch.nn.functional.relu(tensor_X)
     X = tensor_X.numpy()
     Y_ffn = np.matmul(X,W2) + bias2
     return Y_ffn


def Encoder_output(Y_ffn):
     Y_ffn = X_embeding + Y_ffn
     H_encoder = layer_normalisation(Y_ffn)
     return H_encoder


def Encoder_operations(dff):

    # the dff is changing the dimension of projection then reproject it into the orginal projection dimension
     V = np.matmul(Xe,Wv)
     bias1 = np.random.rand(d_model)
     bias2 = np.random.rand(d_model)
     W1 = np.random.rand(d_model,dff)
     W2 = np.random.rand(dff,d_model)
     Y_att = multi_head_projection(V,WO)
     X_1 = layer_normalisation(Xe) + layer_normalisation(Y_att)
     Y_ffn = postion_wise_feed_forward(X_1,W1,W2,bias1,bias2)
     H_encoder = Encoder_output(Y_ffn)
     return H_encoder


H_encoder = Encoder_output(4)
print(H_encoder)


[[-0.32909953  0.47324901 -0.50529203  1.31142568]
 [ 0.85599263  0.01062684 -0.05217266  1.28190791]
 [ 0.36341591 -1.67380123 -0.9281804   1.27017187]
 [ 0.02940137 -2.15117217 -0.77582503  0.81935184]]
